#
#	C A M E R A
#

#	Type: SPECThead


/gate/world/daughters/name 						SPECThead
/gate/world/daughters/insert 					box
/gate/SPECThead/geometry/setXLength  			1. cm
/gate/SPECThead/geometry/setYLength 			11. cm
/gate/SPECThead/geometry/setZLength 			11. cm
#/gate/SPECThead/placement/setTranslation 		{x_placement} 0. 0. mm
/gate/SPECThead/placement/setTranslation 		30. 0. 0. mm
/gate/SPECThead/setMaterial 					Vacuum
/gate/SPECThead/repeaters/insert 				ring
/gate/SPECThead/ring/setRepeatNumber 			1
#/gate/SPECThead/moves/insert 					orbiting
#/gate/SPECThead/orbiting/setSpeed 				1 deg/s
#/gate/SPECThead/orbiting/setPoint1 			0 0 0 cm
#/gate/SPECThead/orbiting/setPoint2 			0 0 1 cm
/gate/SPECThead/vis/setColor 					white
/gate/SPECThead/vis/forceWireframe


# CRYSTAL
# Create the crystal volume

/gate/SPECThead/daughters/name 					crystal
/gate/SPECThead/daughters/insert				box
/gate/crystal/geometry/setXLength 				1. cm
#/gate/crystal/geometry/setXLength 				0.05 cm
/gate/crystal/geometry/setYLength  				11. cm
/gate/crystal/geometry/setZLength  				11. cm
/gate/crystal/placement/setTranslation  		0. 0. 0. cm
/gate/crystal/setMaterial 						{CrystalMaterial}
/gate/crystal/vis/setColor 						blue
#/gate/crystal/vis/forceWireframe
/gate/crystal/vis/forceSolid


# define magnetic field at the center of the system
# z-direction
#/gate/geometry/setMagField 0 0 9.4 T
#/gate/geometry/setMagField 0.0 0.0 0.00001 T
#/gate/geometry/setMagField 0.0 0.0 0.1 T
#/gate/geometry/setMagField 0.0 0.0 3.0 T

# x-direction
#/gate/geometry/setMagField 10.0 0.0 0.0 T

/control/alias camID 1hd

/gate/systems/SPECThead/crystal/attach 			crystal

/gate/crystal/attachCrystalSD

/gate/systems/SPECThead/describe

