#
#	D I G I T I Z E R 
#

/gate/digitizer/Singles/insert adder

/gate/digitizer/Singles/insert			readout
/gate/digitizer/Singles/readout/setDepth        1

/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.10
/gate/digitizer/Singles/blurring/setEnergyOfReference 100. keV

#/gate/digitizer/Singles/insert spblurring
#/gate/digitizer/Singles/spblurring/setSpresolution 2.0 mm
#/gate/digitizer/Singles/spblurring/verbose 0

/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 5. keV

/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 10000. keV
