/gate/verbose Physic    0
/gate/verbose Cuts      0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step      0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam      0
/gate/verbose Volume    1
/gate/verbose Image     1
/gate/verbose Geometry  1
/gate/verbose Core      0

/run/verbose 1
/event/verbose 0
/tracking/verbose 0	      
/control/verbose 1