
/vis/open OGLIQt
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory             1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction           accumulate

/vis/modeling/trajectories/create/drawByParticleID

/vis/scene/add/axes            0 0 0 100 cm
/vis/scene/add/text            110 0 0 cm  10 0 0   X
/vis/scene/add/text            0 110 0 cm  10 0 0   Y
/vis/scene/add/text            0 0 110 cm  10 0 0   Z
/vis/viewer/set/auxiliaryEdge true
