# Box
/gate/world/daughters/name              waterbox
/gate/world/daughters/insert            box
/gate/waterbox/geometry/setXLength      10 cm
/gate/waterbox/geometry/setYLength      10 cm
/gate/waterbox/geometry/setZLength      10 cm
/gate/waterbox/placement/setTranslation 0 0 0 cm
/gate/waterbox/setMaterial Water
/gate/waterbox/vis/setVisible 1
/gate/waterbox/vis/setColor blue

# another object
/gate/waterbox/daughters/name myobject
/gate/waterbox/daughters/insert box
/gate/myobject/geometry/setXLength   3 cm
/gate/myobject/geometry/setYLength   3 cm
/gate/myobject/geometry/setZLength   3 cm
/gate/myobject/placement/setTranslation 2 2 3 cm
/gate/myobject/setMaterial Lead
/gate/myobject/vis/setVisible 1
/gate/myobject/vis/setColor yellow

# Detector plane
/gate/world/daughters/name              detector
/gate/world/daughters/insert            box
/gate/detector/geometry/setXLength      10 cm
/gate/detector/geometry/setYLength      10 cm
/gate/detector/geometry/setZLength      2 mm
/gate/detector/placement/setTranslation 0 0 -20 cm
/gate/detector/setMaterial Lead
/gate/detector/vis/setVisible 1
/gate/detector/vis/setColor red
